# Usamos la misma imagen base de Node
FROM node:22-alpine

# Habilitamos pnpm
RUN corepack enable && corepack prepare pnpm@10.33.2 --activate

# Establecemos la carpeta de trabajo
WORKDIR /app

# Copiamos package.json
COPY package.json ./

# Instalamos las dependencias
RUN pnpm install

# Copiamos el resto del código
COPY . .

# Exponemos el puerto de Vite
EXPOSE 5173

# Arrancamos Vite y le pasamos --host para que sea accesible desde tu navegador
CMD ["pnpm", "run", "dev", "--host"]